### ISSUE TITLE
Text selection handles are broken.

### ISSUE THREAD

**Issue by ChristosBouronikos** [saket/press#32] opened 2019-12-28 16:07 UTC
The handles that appear when selecting text to allow for more precision, are enormous.

![Proof](https://i.imgur.com/eKUQy9B.jpg)

**Comment by saket** [comment] 2019-12-28 16:55
Can you post your device and OS details?

**Comment by ChristosBouronikos** [comment] 2019-12-28 17:51
![Here you go ](https://i.imgur.com/RVytomf.jpg)

Is this the first time you encounter this bug?

**Comment by saket** [comment] 2019-12-28 19:03
Yep. Chinese OEMs are notoriously bad at messing up with system stuff 🤦‍♂. All I'm doing is [applying a ColorFilter](https://github.com/saket/press/blob/f46e6c9a16ae2ad2d53cbffe571049be002237be/androidApp/src/main/java/press/theme/ThemedWidgets.kt#L61) on the selection handle drawables. Not sure what's the issue here. I don't have a Redmi so it's going to be difficult for me to debug this. Wanna help me out?

**Comment by ChristosBouronikos** [comment] 2019-12-28 19:09
How could I do that? I'm not quite sure.
It also seemed weird to me because most apps have the android default handles, despite them being a bit off to their theme and overall color scheme.

**Comment by saket** [comment] 2019-12-28 19:25
> It also seemed weird to me because most apps have the android default handles, despite them being a bit off to their theme and overall color scheme.

Because other apps don't change them at runtime. I want Press to have dynamic themes that can be changed without restarting the app.

> How could I do that? I'm not quite sure.

I'd start by changing the `PorterDuff.Mode` value passed to `setColorFilter` here to make sure that's not the cause: https://github.com/saket/press/blob/f46e6c9a16ae2ad2d53cbffe571049be002237be/androidApp/src/main/java/press/theme/ThemedWidgets.kt#L61

**Comment by ChristosBouronikos** [comment] 2019-12-28 19:34
Oh man I know 0 Kotlin. I'm so sorry. 
I'm glad I found the bug and that you seem to have a method in mind to attack this.

**Comment by SubhrajyotiSen** [comment] 2019-12-29 13:15
I have a test device with MiUI. I can try reproducing the issue and changing the `PorterDuff.Mode` when I  am back at work

**Comment by saket** [comment] 2019-12-29 19:22
@SubhrajyotiSen that would be dope. Thank you!

**Comment by SubhrajyotiSen** [comment] 2019-12-30 07:00
So someone took the device home and is now on vacation. So it might be a few days before I can help with this

**Comment by saket** [comment] 2020-01-01 00:32
sads.gif

I'll also try finding someone with a Xiaomi device when I'm visiting India next month.

**Comment by boyangwang** [comment] 2020-04-07 02:28
Hi, is the issue resolved yet? If not I can test it on a Redmi device today and play with `PorterDuff.Mode` to see if it's the culprit

**Comment by saket** [comment] 2020-04-07 02:34
Please go ahead! I wasn't able to find enough time for this.

**Comment by saket** [comment] 2020-04-10 02:41
@boyangwang was wondering if were able to find anything?

**Comment by drakeet** [comment] 2020-04-27 02:40
MIUI modified the native cursor-related API, so it doesn't support to modify the cursor or selection handles. It is currently recommended to skip MIUI for your theme logic. I have helped to report this problem to the MIUI team, and it should be fixed in the future.

**Comment by saket** [comment] 2020-10-25 06:09
@ChristosBouronikos can you check if the latest release change anything for you?

**Comment by ChristosBouronikos** [comment] 2020-11-09 20:49
@saket  I'm on a new OnePlus phone, so I had to find time to dig into my old Xiaomi phone.

Got the latest build.

Handles seem to be fine now. Just as I would expect.

Thanks for the good work!

**Comment by saket** [comment] 2020-11-09 21:33
Awesome, thanks for checking!

**Closed as completed by saket** 2020-11-09 21:33 UTC
Labels: help wanted, android
